### ISSUE TITLE
Any way to limit image size (either dimensions or file size)?

### ISSUE THREAD

**Issue by ImTheKeyMaster** [Tapfiliate/tapatar#14]
Hi,
Had a user upload a 4MB picture to use as an avatar.  Really put a drag on the application.  I did not see any properties that could be set.  Is there a known way of limiting users to certain sizes?  I'm sure this is a concern for others as well.  

Thanks!

**Comment by kurtextrem** [comment]
You should check that on the backend as "hackers" could upload larger images anyway if you only check client-side.

**Comment by ImTheKeyMaster** [comment]
Yes.  Good call.  I ended up using the powerful and free ImageResizer (http://imageresizing.net) to reduce the image to 70px x 70px before saving into the DB.  Thanks!
