### ISSUE TITLE
Data-uri a problem or a solution?

### ISSUE THREAD

**Issue by paschaldev** [Tapfiliate/tapatar#5]
Thank you very much for this plugin.. I love it and currently using it but that means I need to add the avatrs to database directly since its data-uri... Read some bad articles on data-uri and I was drawn back... Is there a way we can get the file and store it locally with our own preferred name?? I'm a noob and please I need help..

**Comment by thomask** [comment]
Can you provide some sources for that?  Furthermore, you can use any backend technologie to generate images from the data URI.

Closing as this is not something that will be added in Tapatar.

**Comment by paschaldev** [comment]
I really cant provide a source at the moment, it was some google search. The major issue was that data-uri is slower on mobile... I will stick to using data-uri & database since i'm running a small project. I never knew you could convert data-uri to file on backend. Maybe i'll try that. Thank you thomask
